### ISSUE TITLE
No tests on pull requests?

### ISSUE THREAD

**Issue by skalee** [metanorma/metanorma-build-scripts#24]
Is there any good reason for:

```
on: [push]
```

instead of:

```
on: [push, pull_request]
```

Running tests on `push` event will run tests on the last commit of given branch, but will not take into account commits, which are present on `master` branch, but not on tested branch. Also, I suppose, no tests will be run for pull requests coming from forked repositories.

**Comment by ronaldtse** [comment]
@skalee yes you’re right and that’s what we have to fix across repos. We currently use the “ci-master” tool/repo to do so, but I need some time to find out how to use it...

**Comment by CAMOBAP795** [comment]
for now, we are using 

```
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
```

I think this should fix the problem, @ronaldtse @skalee let me know if you see some issues with this implementation

**Comment by ronaldtse** [comment]
Is there a difference with this?

```
on:
  push:
    branches: [ master ]
  pull_request:
```
