### ISSUE TITLE
Repair GitHub Action build scripts for relaton-iev

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-build-scripts#29]
The relaton-iev build scripts contain

````
steps:
      - uses: actions/checkout@master
      with:
          submodules: recursive
````

submodules is not supported in GitHub Actions, and there are not submodules in relaton-iev anyway. I could not find any instances of submodules in metanorma/metanorma-build-scripts, but just in case, please check that submodules are not being added now into any GitHub Action scripts. (This is the only instance I could find in my local copy of relaton and metanorma.) I have deleted the lines from the build scripts.
