### ISSUE TITLE
Allow usage of private containers in sample-docker workflow (and probably others)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-build-scripts#80]
These two lines should be flexible enough to allow people to use their private containers (GHCR or Docker Hub) and provide private credentials:

https://github.com/metanorma/metanorma-build-scripts/blob/28c83307924210d1ba7329617c1904ac864efc63/.github/workflows/sample-docker.yml#L17-L18

Right the private credentials are provided like this:
https://github.com/metanorma/mn-samples-nist/blob/41b2802c1652c339ab7681cfc63a3b04517017f2/.github/workflows/docker.yml#L18-L22

```yaml
    container:
      image: ghcr.io/metanorma/xxx:latest
      credentials:
        username: mona
        password: ${{ secrets.XXX_PAT_TOKEN }}
```

This is related to https://github.com/metanorma/mn-samples-nist/issues/70
